server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://192.168.209.134:10087/eureka
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.209.134-1703a:3306/1703a?serverTimezone=UTC
  jackson:
    date-format: yyyy-MM-dd
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true

